// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"

	"github.com/ducthangng/GeoFleet/app/internal/infrastructure"
)

// Injectors from wire.go:

func BuildKafkaListener(ctx context.Context) (*infrastructure.KafkaConsumer, error) {
	pool, err := ProvideDBPool(ctx)
	if err != nil {
		return nil, err
	}
	queries := ProvideRepository(pool)
	client := ProvideRedis(ctx)
	trackingService := ProvideUserUsecase(queries, client)
	reader := ProvideKafkaReader(ctx)
	kafkaConsumer := infrastructure.NewKafkaConsumer(trackingService, reader)
	return kafkaConsumer, nil
}
