// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TrackingServiceCoordinate struct {
	ID         int64
	UserID     pgtype.UUID
	Coordinate interface{}
	CreatedAt  pgtype.Timestamptz
}

type TrackingServiceRideCoordinate struct {
	ID         int64
	RideID     pgtype.UUID
	UserID     pgtype.UUID
	Coordinate interface{}
	Velocity   pgtype.Float8
	CreatedAt  pgtype.Timestamptz
}
