// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetCoordinateByUser(ctx context.Context, userID pgtype.UUID) ([]TrackingServiceCoordinate, error)
	GetCoordinateInRide(ctx context.Context, rideID pgtype.UUID) ([]TrackingServiceRideCoordinate, error)
	GetCoordinateInRideByUser(ctx context.Context, arg GetCoordinateInRideByUserParams) ([]TrackingServiceRideCoordinate, error)
	InsertCoordinate(ctx context.Context, arg InsertCoordinateParams) (TrackingServiceCoordinate, error)
	InsertRideCoordinate(ctx context.Context, arg InsertRideCoordinateParams) (TrackingServiceRideCoordinate, error)
}

var _ Querier = (*Queries)(nil)
