// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// cast to bytea so that GO knows it must be []byte
	GetCoordinateByUser(ctx context.Context, userID uuid.UUID) ([]GetCoordinateByUserRow, error)
	GetCoordinateInRide(ctx context.Context, rideID uuid.UUID) ([]TrackingServiceRideCoordinate, error)
	GetCoordinateInRideByUser(ctx context.Context, arg GetCoordinateInRideByUserParams) ([]TrackingServiceRideCoordinate, error)
	InsertCoordinate(ctx context.Context, arg InsertCoordinateParams) (InsertCoordinateRow, error)
	InsertRideCoordinate(ctx context.Context, arg InsertRideCoordinateParams) (InsertRideCoordinateRow, error)
}

var _ Querier = (*Queries)(nil)
