// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCoordinateByUser = `-- name: GetCoordinateByUser :many
SELECT id, user_id, coordinate, created_at 
FROM tracking_service.coordinate 
WHERE user_id = $1
`

func (q *Queries) GetCoordinateByUser(ctx context.Context, userID pgtype.UUID) ([]TrackingServiceCoordinate, error) {
	rows, err := q.db.Query(ctx, getCoordinateByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingServiceCoordinate
	for rows.Next() {
		var i TrackingServiceCoordinate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Coordinate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoordinateInRide = `-- name: GetCoordinateInRide :many
SELECT id, ride_id, user_id, coordinate, velocity, created_at 
FROM tracking_service.ride_coordinate 
WHERE ride_id = $1
`

func (q *Queries) GetCoordinateInRide(ctx context.Context, rideID pgtype.UUID) ([]TrackingServiceRideCoordinate, error) {
	rows, err := q.db.Query(ctx, getCoordinateInRide, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingServiceRideCoordinate
	for rows.Next() {
		var i TrackingServiceRideCoordinate
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.UserID,
			&i.Coordinate,
			&i.Velocity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoordinateInRideByUser = `-- name: GetCoordinateInRideByUser :many
SELECT id, ride_id, user_id, coordinate, velocity, created_at 
FROM tracking_service.ride_coordinate 
WHERE ride_id = $1 and user_id = $2
`

type GetCoordinateInRideByUserParams struct {
	RideID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetCoordinateInRideByUser(ctx context.Context, arg GetCoordinateInRideByUserParams) ([]TrackingServiceRideCoordinate, error) {
	rows, err := q.db.Query(ctx, getCoordinateInRideByUser, arg.RideID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingServiceRideCoordinate
	for rows.Next() {
		var i TrackingServiceRideCoordinate
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.UserID,
			&i.Coordinate,
			&i.Velocity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCoordinate = `-- name: InsertCoordinate :one
INSERT INTO tracking_service.coordinate (
    user_id, coordinate
) VALUES (
    $1, $2
) 
RETURNING id, user_id, coordinate, created_at
`

type InsertCoordinateParams struct {
	UserID     pgtype.UUID
	Coordinate interface{}
}

func (q *Queries) InsertCoordinate(ctx context.Context, arg InsertCoordinateParams) (TrackingServiceCoordinate, error) {
	row := q.db.QueryRow(ctx, insertCoordinate, arg.UserID, arg.Coordinate)
	var i TrackingServiceCoordinate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Coordinate,
		&i.CreatedAt,
	)
	return i, err
}

const insertRideCoordinate = `-- name: InsertRideCoordinate :one
INSERT INTO tracking_service.ride_coordinate (
    user_id, ride_id, coordinate, velocity
) VALUES (
    $1, $2, $3, $4
) 
RETURNING id, ride_id, user_id, coordinate, velocity, created_at
`

type InsertRideCoordinateParams struct {
	UserID     pgtype.UUID
	RideID     pgtype.UUID
	Coordinate interface{}
	Velocity   pgtype.Float8
}

func (q *Queries) InsertRideCoordinate(ctx context.Context, arg InsertRideCoordinateParams) (TrackingServiceRideCoordinate, error) {
	row := q.db.QueryRow(ctx, insertRideCoordinate,
		arg.UserID,
		arg.RideID,
		arg.Coordinate,
		arg.Velocity,
	)
	var i TrackingServiceRideCoordinate
	err := row.Scan(
		&i.ID,
		&i.RideID,
		&i.UserID,
		&i.Coordinate,
		&i.Velocity,
		&i.CreatedAt,
	)
	return i, err
}
