// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracking_queries.sql

package postgresql

import (
	"context"

	"github.com/ducthangng/GeoFleet/app/internal/domain/entity"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCoordinateByUser = `-- name: GetCoordinateByUser :many
SELECT id, user_id, coordinate::bytea as coordinate, created_at
FROM tracking_service.coordinate 
WHERE user_id = $1
`

type GetCoordinateByUserRow struct {
	ID         int64
	UserID     uuid.UUID
	Coordinate []byte
	CreatedAt  pgtype.Timestamptz
}

// cast to bytea so that GO knows it must be []byte
func (q *Queries) GetCoordinateByUser(ctx context.Context, userID uuid.UUID) ([]GetCoordinateByUserRow, error) {
	rows, err := q.db.Query(ctx, getCoordinateByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoordinateByUserRow
	for rows.Next() {
		var i GetCoordinateByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Coordinate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoordinateInRide = `-- name: GetCoordinateInRide :many
SELECT id, ride_id, user_id, coordinate, velocity, created_at 
FROM tracking_service.ride_coordinate 
WHERE ride_id = $1
`

func (q *Queries) GetCoordinateInRide(ctx context.Context, rideID uuid.UUID) ([]TrackingServiceRideCoordinate, error) {
	rows, err := q.db.Query(ctx, getCoordinateInRide, rideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingServiceRideCoordinate
	for rows.Next() {
		var i TrackingServiceRideCoordinate
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.UserID,
			&i.Coordinate,
			&i.Velocity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoordinateInRideByUser = `-- name: GetCoordinateInRideByUser :many
SELECT id, ride_id, user_id, coordinate, velocity, created_at 
FROM tracking_service.ride_coordinate 
WHERE ride_id = $1 and user_id = $2
`

type GetCoordinateInRideByUserParams struct {
	RideID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCoordinateInRideByUser(ctx context.Context, arg GetCoordinateInRideByUserParams) ([]TrackingServiceRideCoordinate, error) {
	rows, err := q.db.Query(ctx, getCoordinateInRideByUser, arg.RideID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackingServiceRideCoordinate
	for rows.Next() {
		var i TrackingServiceRideCoordinate
		if err := rows.Scan(
			&i.ID,
			&i.RideID,
			&i.UserID,
			&i.Coordinate,
			&i.Velocity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCoordinate = `-- name: InsertCoordinate :one
INSERT INTO tracking_service.coordinate (
    user_id, coordinate
) VALUES (
    $1, 
    ST_SetSRID(ST_MakePoint($2::float8, $3::float8), 4326)
) 
RETURNING id, ST_AsBinary(coordinate) as coordinate, created_at
`

type InsertCoordinateParams struct {
	UserID    uuid.UUID
	Longitude float64
	Latitude  float64
}

type InsertCoordinateRow struct {
	ID         int64
	Coordinate interface{}
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertCoordinate(ctx context.Context, arg InsertCoordinateParams) (InsertCoordinateRow, error) {
	row := q.db.QueryRow(ctx, insertCoordinate, arg.UserID, arg.Longitude, arg.Latitude)
	var i InsertCoordinateRow
	err := row.Scan(&i.ID, &i.Coordinate, &i.CreatedAt)
	return i, err
}

const insertRideCoordinate = `-- name: InsertRideCoordinate :one
INSERT INTO tracking_service.ride_coordinate (
    user_id, ride_id, coordinate, velocity
) VALUES (
    $1, $2, $3, $4
) 
RETURNING id, coordinate::bytea as coordinate, created_at
`

type InsertRideCoordinateParams struct {
	UserID     uuid.UUID
	RideID     uuid.UUID
	Coordinate entity.Point
	Velocity   pgtype.Float8
}

type InsertRideCoordinateRow struct {
	ID         int64
	Coordinate []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertRideCoordinate(ctx context.Context, arg InsertRideCoordinateParams) (InsertRideCoordinateRow, error) {
	row := q.db.QueryRow(ctx, insertRideCoordinate,
		arg.UserID,
		arg.RideID,
		arg.Coordinate,
		arg.Velocity,
	)
	var i InsertRideCoordinateRow
	err := row.Scan(&i.ID, &i.Coordinate, &i.CreatedAt)
	return i, err
}
